site_name: 'docs.enclave.io'

theme:
  name: 'material'

  features:
    - navigation.sections
    - navigation.tabs
    #- navigation.tracking
    #- navigation.expand
    #- navigation.indexes
    #- navigation.top
    #- toc.integrate

  static_templates:
    - 404.html

  # necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  icon:
    logo: logo
#  palette:
#    primary: red

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enclave-networks
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/enclavenetworks/enclave
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/enclavenetworks
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/enclave-networks/
  # enable documentation versioning support 
  version:
    provider: mike

google_analytics:
  - G-KZSMYSG7EP
  - auto

nav:
  - Home:
    - Documentation: index.md
#    - Community: community.md
#    - Glossary: glossary.md

  - Quick Start Guide:  
    - Getting started: quick-start.md

  - Handbook:
    - Introduction: handbook/introduction.md
    - Installation:
      - Windows: handbook/install/windows.md
      - Linux:
        - Ubuntu / Debian: handbook/install/ubuntu.md
#        - CentOS / RHEL: handbook/install/rhel.md
#        - Fedora: handbook/install/fedora.md
#        - Amazon Linux: handbook/install/amazon-linux.md
#        - Arch Linux: handbook/install/arch.md
#        - Raspbian: handbook/install/raspbian.md
#        - Docker: handbook/install/docker.md
#        - Kubernetes: handbook/install/kubernetes.md
#        - Synology NAS: handbook/install/synology-nas.md

#      - Running Enclave:
#        - As a service: handbook/creating-your-site.md
#        - Interactively: handbook/publishing-your-site.md

#        - Fabric commands (CLI):
#          - All:
#            - status: reference/cli/status.md
#            - enrol: reference/cli/enrol.md
#            - start: reference/cli/start.md
#            - stop: reference/cli/stop.md
#            - add: reference/cli/add.md
#            - remove: reference/cli/remove.md
#            - enable: reference/cli/enable.md
#            - disable: reference/cli/disable.md
#            - help: reference/cli/help.md
#            - version: reference/cli/version.md
#          - Windows only:
#            - list-adapters: reference/cli/list-adapters.md
#            - install-adapter: reference/cli/install-adapter.md
#            - remove-adapter: reference/cli/remove-adapter.md

    - Core Concepts:
#      - Principles: handbook/principles.md
      - Architecture: handbook/architecture.md
#      - Endpoint management: handbook/endpoint-management.md
#      - Enrolment keys: handbook/enrolment.md
#      - Policies and tags: handbook/tags-and-policies.md
#      - IP addresses: handbook/ip-addresses.md
#      - DNS: handbook/dns.md

#      - Connectivity:
#        - Requirements: handbook/formatting.md
#        - NAT traversal: handbook/variables.md
#        - Agent telemetry: handbook/footnotes.md

#      - Security:
#        - Threat model: handbook/threat-model.md
#        - Security considerations: handbook/security-considerations.md
#        - Certificates: handbook/certificates.md
#        - Encryption: handbook/encryption.md
#        - Key management: handbook/key-management.md

#      - Configuration Files:
#        - Windows: handbook/configs.md
#        - Linux: handbook/configs.md

#    - Enclave Networking:
#      - ARP: handbook/arp.md
#      - Multicast: handbook/multicast.md

  - REST API:
      Overview: reference/api/index.md
      Reference: reference/api/reference.md
      Guides: reference/api/guides.md

  - Tutorials: tutorials/index.md

  - KB & Troubleshooting: troubleshooting/index.md

  - Support:
    - Contact us: support/contact.md
    - Billing:
      - Frequently asked questions: support/billing.md
    - Account:
      - Ownership, transfer and closure: support/account.md
